version: '3.4'

services:
  accubatch:
    image: ${DOCKER_REGISTRY}accubatch
    build:
      context: .
      dockerfile: Services\AccuBatch\Dockerfile

  accumarkers:
    image: ${DOCKER_REGISTRY}accumarkers
    build:
      context: .
      dockerfile: Services\AccuMarkers\Dockerfile


  accuorders:
    image: ${DOCKER_REGISTRY}accuorders
    build:
      context: .
      dockerfile: Services\AccuOrders\Dockerfile


  batchfilecreator:
    image: ${DOCKER_REGISTRY}batchfilecreator
    build:
      context: .
      dockerfile: Tasks\BatchFileCreator\Dockerfile


  accumarkstoragearea:
    image: ${DOCKER_REGISTRY}accumarkstoragearea
    build:
      context: .
      dockerfile: Services\AccuMarkStorageArea\Dockerfile


  accumarkmarkers:
    image: ${DOCKER_REGISTRY}accumarkmarkers
    build:
      context: .
      dockerfile: Services\AccuMarkMarkers\Dockerfile


  accumarkorders:
    image: ${DOCKER_REGISTRY}accumarkorders
    build:
      context: .
      dockerfile: Services\AccuMarkOrders\Dockerfile


  accumarkdeletemarkerafterexport:
    image: ${DOCKER_REGISTRY}accumarkdeletemarkerafterexport
    build:
      context: .
      dockerfile: Services\AccuMarkDeleteMarkerAfterExport\Dockerfile


  accumarkdeletemarkerafterplot:
    image: ${DOCKER_REGISTRY}accumarkdeletemarkerafterplot
    build:
      context: .
      dockerfile: Services\AccuMarkDeleteMarkerAfterPlot\Dockerfile

